spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: chirp-backend-credentials@sandbox5304ae847e744a399a4a896afb07ddd9.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  email:
    url: "https://chirp.juandroiddev.com"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origins: "http://chirp.juandroiddev.com"